name: goodwalls-app publish

on:
  push:
    tags:
      - v*.*.*
    branches:
      - main
      - master

permissions:
  contents: write
  packages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
  ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
  ANDROID_KEYSTORE_PATH: "./goodwalls.jks"

  FIREBASE_JSON_SSL_KEY: ${{ secrets.FIREBASE_JSON_SSL_KEY }}
  FIREBASE_JSON_SSL_IV: ${{ secrets.FIREBASE_JSON_SSL_IV }}

  WORKING_DIRECTORY: "${{ github.workspace }}/android_app"
  FIREBASE_JSON_PATH: "${{ github.workspace }}/android_app/app"
  GIT_TAG: ${{ github.ref_name }}
  
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }} # Set the working directory for all steps in this job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - uses: android-actions/setup-android@v3
      - run: |
          yes | sdkmanager 'platforms;android-35' 'build-tools;35.0.0' || { echo "sdkmanager failed. Check above logs for errors."; exit 1; }

          # Find the exact directory where apksigner executable resides
          APKSIGNER_DIR=$(find "${ANDROID_HOME}/build-tools/" -name "apksigner" -type f -print -quit | xargs dirname)
          
          # Add this build-tools directory to the PATH for subsequent steps
          echo "PATH=$PATH:$APKSIGNER_DIR" >> $GITHUB_ENV

      - name: Decrypt keystore
        run: |
          cd app
          openssl aes-256-cbc -K ${{ env.FIREBASE_JSON_SSL_KEY }} -iv ${{ env.FIREBASE_JSON_SSL_IV }} -in ${{ env.FIREBASE_JSON_PATH }}/google-services.json.enc -out ${{ env.FIREBASE_JSON_PATH }}/google-services.json -d

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Build Release AAB
        run: ./gradlew bundleRelease
     
      - name: Sign APK with Apksigner
        run: |
          # If your keypass is different from storepass, you'll need ANDROID_KEY_PASSWORD secret for it.
           apksigner sign --ks "${{ env.ANDROID_KEYSTORE_PATH }}"  --ks-pass pass:"${{ env.ANDROID_KEYSTORE_PASSWORD }}"  --ks-key-alias ${{ env.ANDROID_KEY_ALIAS }}  --key-pass pass:"${{ env.ANDROID_KEY_PASSWORD }}" ./app/release/*.apk

           
      - name: Sign AAB with Jarsigner
        run: |
          # If your keypass is different from storepass, you'll need ANDROID_KEY_PASSWORD secret for it.
          jarsigner -keystore "${{ env.ANDROID_KEYSTORE_PATH }}" --storepass "${{ env.ANDROID_KEYSTORE_PASSWORD }}" ./app/release/*.aab ${{ env.ANDROID_KEY_ALIAS }}


      - name: Rename release files with tag name or snapshot
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            NAME="goodwalls-${{ env.GIT_TAG }}"
          else
            NAME="goodwalls-snapshot"
          fi
          
          mv ./app/release/app-release.apk ./app/release/${NAME}.apk
          mv ./app/release/app-release.aab ./app/release/${NAME}.aab
          

      - name: GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft : false
          make_latest: true
          files: |
            ./app/release/*.aab
            ./app/release/*.apk